---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: md-linter-pipeline
spec:
  workspaces:
    - name: pipeline-shared-data
      description: |
        This workspace stores the cloned repository and is available to all steps
  tasks
    - name: clone-repository
      params:
        name: url
          value: https://github.com/upslopeio/lint-markdown-files
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: md-lint-run #lint mardown
      taskRef:
        name: markdown-lint
      runAfter:
        - clone-repository
      workspaces:
        - name: shared-workspace
          workspace: pipeline-shared-data
      params:
        - name: args
          value: ["."]
